# This is a basic workflow to help you get started with Actions

name: Doom

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install emacs 
        run: sudo apt-get install -y emacs
      - name: Clone doom emacs and install
        run: |
          git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
          yes | ~/.config/emacs/bin/doom install
      - name: Show current dir and home 
        run: |
          ls -lart
          ls -lart ~/.config
          ls -lart ~/.config/emacs
          ls -lart ~/.config/doom
      - name: Download doom folder configs from dotfiles repository 
        run: curl https://codeload.github.com/notarock/dotfiles/tar.gz/macos | tar -xz --strip=2 dotfiles-macos/notarock/doom.d
      - name: Place downloaded folder in ~/.config 
        run: rm -rf ~/.config/doom && mv doom.d ~/.config/doom
      - name: Doom sync with personnal config 
        run: ~/.config/emacs/bin/doom sync
      - name: Compress emacs and doom config to upload as artifact
        run: |
          cp -r ~/.config/emacs ./emacs
          cp -r ~/.config/doom ./doom
          tar -czvf doomemacs-config.tar.gz ./emacs ./doom
      - name: Upload doomemacs config
        uses: actions/upload-artifact@v4
        with:
          name: doomemacs-config
          path: doomemacs-config.tar.gz


        




